region-overrides:
  houses:
    # This will override all BLAST_FURNACES in the HOUSES region with the WEAPONS pool.
    BLAST_FURNACE: "weapons"
# Useful for children regions to exclude.
# Inactive regions will TAKE PRIORITY
inactive-regions:
active-regions:
randomize-durability: true
random-min-durability-percent: 10
expire-time: 10
expire-time-unit: MINUTES
stackable-items:
  - ARROW
  - FLINT
  - FEATHER
  - BONE
  - STICK
stack-minimum: 0
stack-maximum: 99
per-player-pools: false
pools:
  food:
    blocks:
      BLAST_FURNACE: { }
      SMOKER: { }
      DROPPER: { }
      RED_SHULKER_BOX: { }
      FURNACE: { }
    min-picked-slots: 4
    max-picked-slots: 4
    fill-strategy: "SLOTTED_RANDOM"
  armor:
    blocks:
      WHITE_SHULKER_BOX: { }
      LIGHT_BLUE_SHULKER_BOX: { }
      LOOM: { }
      MAGENTA_SHULKER_BOX: { }
      PURPLE_SHULKER_BOX: { }
    min-picked-slots: 4
    max-picked-slots: 4
    fill-strategy: "SLOTTED_RANDOM"
  random:
    blocks:
      BARREL: { }
      CHEST: { }
      LIGHT_GRAY_SHULKER_BOX: { }
      GRAY_SHULKER_BOX: { }
      PINK_SHULKER_BOX: { }
      CHISELED_STONE_BRICKS: { }
      INFESTED_CHISELED_STONE_BRICKS: { }
    min-picked-slots: 4
    max-picked-slots: 4
    fill-strategy: "SLOTTED_RANDOM"
  drinks_health:
    blocks:
      SHULKER_BOX: { }
      BLACK_SHULKER_BOX: { }
      BROWN_SHULKER_BOX: { }
      CYAN_SHULKER_BOX: { }
      GREEN_SHULKER_BOX: { }
    min-picked-slots: 4
    max-picked-slots: 4
    fill-strategy: "SLOTTED_RANDOM"
  weapons:
    blocks:
      BLUE_SHULKER_BOX: { }
      YELLOW_SHULKER_BOX: { }
      OBSERVER: { }
      ORANGE_SHULKER_BOX: { }
      LIME_SHULKER_BOX: { }
    min-picked-slots: 4
    max-picked-slots: 4
    fill-strategy: "SLOTTED_RANDOM"
  junk:
    blocks:
      FLETCHING_TABLE: { }
      DEAD_TUBE_CORAL: { }
      DEAD_HORN_CORAL: { }
      DEAD_BRAIN_CORAL: { }
      SMITHING_TABLE: { }
    min-picked-slots: 4
    max-picked-slots: 4
    fill-strategy: "SLOTTED_RANDOM"